### PR TITLE
utils.py: Fix "invalid escape sequence \(" warning

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Comment by glebm** [comment]
Please merge?

**Comment by jiaaro** [comment]
Could you add a test or possibly just explain here how to reproduce the problem you were encountering before this change?

**Comment by glebm** [comment]
Simply running with Python 3 with warnings `-Wall` triggers this warning. Rightly so, because e.g. `"\("` is not a valid backslash-escape sequence.

```console
$ echo 'print("\\(")' | python -Wall 
<stdin>:1: DeprecationWarning: invalid escape sequence \(
\(
```

**Comment by unitof** [comment]
This still hasn't made it to a release, causing the warning to appear: #790. I'm seeing it running ManimCommunity/manim.

**Pull request merged**
