### PR TITLE
add current dir to program search locations

### PR DESCRIPTION
**Pull request by clugg**
add os.curdir to the list of environment dirs when searching for
programs using which()

### CODE REVIEW

**Comment by jiaaro** [comment]
Seems like the current directory would be the first place to look (i.e., would override a system install) – don't you think?

**Comment by jiaaro** [comment]
Though on the other hand, I think this is non-standard behavior

**Comment by clugg** [comment]
Either way, I expected it to find ffmpeg in the directory I was running the script from and it didn't. Not sure whether it should be before or after every other path.

**Comment by jiaaro** [comment]
I'm still going back and forth on this - I'm not sure it's a good idea since it's not common behavior to look for system installed executables in the current working directory. Are you aware of the following? Would they solve your particular use case?

You can tell pydub where the converter program is manually any time before you actually use it – like so:

```python
from pydub import AudioSegment

AudioSegment.converter = "/path/to/ffmpeg"
```

**Comment by clugg** [comment]
It would solve my case specifically, but I was under the impression that looking in the working directory was part of the default behaviour, or at least it is on Windows.

**Pull request merged**
