### PR TITLE
Issue #316

### PR DESCRIPTION
**Pull request by anubhav-narayan**
Added an Equaliser Function

### CODE REVIEW

**Comment by jiaaro** [comment]
looks good, but should probably go in scipy_effects.py since it uses the (order=2) argument which only the scipy filters support

**Comment by anubhav-narayan** [comment]
An Independent mode will follow soon on the Equaliser

**Comment by anubhav-narayan** [comment]
Added a Channel Independent Mode
#492

**Review by jiaaro — APPROVED** [review]

**Comment by jiaaro** [comment]
this is included in another (merged) PR

**Pull request closed without merging**
