### PR TITLE
Update audio_segment.py

### PR DESCRIPTION
**Pull request by jmcmellen**
I added a property to get the peak sample level in dB, what do you think?

### CODE REVIEW

**Comment by jiaaro** [comment]
Interesting idea. Curious about why you chose to round the value.

`audio_segment.peak` strikes me as a little confusing - personally, I wouldn't be sure what I was getting.

what do you think of `audio_segment.max_dBFS` or `audio_segment.peak_dBFS` as potential names (in terms of obviousness, I'm shooting for maximum obviousness :smile: )

**Comment by jmcmellen** [comment]
I work in radio broadcasting, and in the industry no one I'm aware of uses more than one decimal place, but that is simply a custom. You don't have to round it, I guess it's just more what I'm used to. Peak is also a term that is common, but max_dBFS and peak_dBFS are both clear descriptive terms.

I have found myself using this property frequently, because if you want to add some dB's without clipping, it is useful to know how much headroom you have to work with.

You made some excellent suggestions, maybe max_dBFS would be best since it is derived from max?

**Comment by jiaaro** [comment]
ok I like the idea - `max_dBFS` works for me :+1: 

The reason to avoid rounding is so that users of the value can compare with other segments that are close, or for instance, if it rounds UP you might end up clipping by accident in a case like `audio_segment.apply_gain(-audio.max_dBFS)` (which would, in theory, normalize the audio segment)

**Comment by jiaaro** [comment]
oh! forgot to mention, before this can get merged it needs to be added to the docs (`API.markdown`) and unit test coverage (`test/test.py`)

**Comment by jiaaro** [comment]
and of course, feel free to add yourself to the `AUTHORS` file as well as part of the PR (if not I'll just add your name and github username after merging)

**Comment by jmcmellen** [comment]
Ok, good point.

Please bear with me, this is actually my first PR, do I need to close it, make those changes and do a new PR? What works best for your workflow?

**Comment by jiaaro** [comment]
you can just make the changes on in the branch you used for the PR (your `master` branch in this case) and they will be part of the PR

**Comment by jmcmellen** [comment]
Ok, thanks. I'll try to get it done today. Thanks for your work on this project! It's very useful!

**Comment by jmcmellen** [comment]
Sorry it's taken some time to get this done. I hope I covered everything.

**Comment by jiaaro** [comment]
@jmcmellen no prob - looks good.

merged!

**Pull request merged**
