### PR TITLE
Added cover option to export function.

### PR DESCRIPTION
**Pull request by dacacioa**
Added cover option to export function that allows to define a image file as cover to exported file.

### CODE REVIEW

**Comment by jiaaro** [comment]
looks good, this is very cool, is there a way to determine whether the format being used supports a cover image? 

Letting ffmpeg's error bubble up is an option, but it usually gives pretty unhelpful error messages (at least for someone using pydub)

**Comment by dacacioa** [comment]
hi, sorry for the delay in the answer. I tryed it with jpg and png format and works fine, but it Works if your have your ffmpeg compiled with the appropiate encoder/decoder. I will check if it supports any image format natively and if exists some system package dependency for every image format.

I will try to give you and answer next week.

**Comment by jiaaro** [comment]
Cool that's good stuff to know (I meant like MP3 vs WAV and FLAC – I don't think wav supports cover images, for example)

Thanks for your work on this, it's a cool thing to be able to support. May also appeal to podcasters :)

**Comment by dacacioa** [comment]
Hi,

I did some test and you are right: it only works in MP3 (it seems that WAV doesn't allow it and FLAC needs differents kinds of parameter). I tested it with different kinds of image format (jpeg, bmp, tif, png...) with ffmpeg base package in Ubuntu 14.04 and higher and it works fine.

Maybe, we can add this functionality for MP3 files and add it to another sound file types in the future.

What do you think?

**Comment by jiaaro** [comment]
yeah definitely makes sense, as long as there's a check that people passing in the artwork are exporting an mp3 (and an descriptive exception otherwise)

**Comment by dacacioa** [comment]
Did you check my last commit?

It looks like:

```python
         if cover is not None:
 -            if cover.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp')) and format == "mp3":		 +            if cover.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.tif')) and format == "mp3":
                  conversion_command.extend(["-i" , cover, "-map", "0", "-map", "1"])		                  conversion_command.extend(["-i" , cover, "-map", "0", "-map", "1"])
              else:		              else:
 -                raise AttributeError("Only .tif, .jpg, .bmp, .jpeg and .png image file types are supported and mp3 sound files.")		 +                raise AttributeError("Nowadays put a cover is only supported by MP3 files. The allowed image formats are: .tif, .jpg, .bmp, .jpeg and .png.")
```

I checked the extension of image file and check that it only can user with MP3 export format file. Otherwise  I launch a AttributeError exception with a descriptive text. 

What dou you think?

**Comment by jiaaro** [comment]
oh you're right!

**Comment by jiaaro** [comment]
TODO: (You can do any of these and update the PR or I will do them when I have some time to work on it)

- [ ] Update API.markdown to reflect the new export option
- [ ] Add some basic unit tests to make sure this works correctly (now and in the future when other things are changed)
- [ ] Support passing in a file-like object instead of a file path for the cover
- [ ] cut a new release for PyPI

**Pull request merged**
