### PR TITLE
Fix, replaced the choice of the key to get

### PR DESCRIPTION
**Pull request by skar404**

### CODE REVIEW

**Comment by skar404** [comment]
https://github.com/jiaaro/pydub/issues/285

**Comment by jiaaro** [comment]
Does this account for the change in format mentioned in #285 ?

If not, maybe it'd be easier to get the json formatted output from ffprobe/avprobe?

**Comment by skar404** [comment]
@jiaaro This is a bug fix from: https://github.com/jiaaro/pydub/blob/master/pydub/utils.py#L284, (because it's not else, for this reason `sample_fmt` may not exist), 

Unfortunately not so well while I understand as `utils.py` works c ffprobe/avprobe, for this reason did not want to climb there.

Sorry, but the text was translated from the Russian language, so I attach the original:

>Это исправления ошибки со строки: https://github.com/jiaaro/pydub/blob/master/pydub/utils.py#L284, (потому как не else, по этой причине `sample_fmt` может не существовать ) 
>К сожалению пока еще не очень хорошо пока понимаю как `utils.py` работает c ffprobe/avprobe, по этой причине не хотел туда лезть.

**Comment by skar404** [comment]
@jiaaro on macOS, almost all tests fall 
Log: https://gist.github.com/skar404/c31339794d79eca2dfe1c78d68d253ab

**Comment by skar404** [comment]
updated the parser format for macOS.

**Pull request merged**
