### PR TITLE
fix inconsistent handling of 8-bit audio

### PR DESCRIPTION
**Pull request by GreyAlien502**
This solves the problem where 8-bit audio is inconsistently treated as unsigned and signed integers.
This fix converts to and from signed integers when reading or writing 8-bit wav files.

The rms and set_sample_width methods of the AudioSegment class tried to handle the data as unsigned,
but this would not be enough, since audioop's methods all treat the audio like signed integers.

The codec used for reading from 8-bit wav files is changed to pcm_u8 from pcm_s8.

This will fix issues #417. #367, and the garbled audio problem mentioned in #381.

Tests were added to compare the RMS values for 8-bit audio segments created from a variety of ways to ensure they are all the same.

### CODE REVIEW

**Comment by jiaaro** [comment]
This looks great - would you be able to address the failing unit tests?

**Comment by GreyAlien502** [comment]
Okay, i've fixed the tests.
I guess you are fine with merging all these changes in one pull request,
so i'll go ahead and close the one i made for just the tests.

**Comment by GreyAlien502** [comment]
Okay, i've fixed the tests.
I guess you are fine with merging all these changes in one pull request,
so i'll go ahead and close the one i made for just the fixes to the tests.

**Comment by GreyAlien502** [comment]
This also fixes issue #409.

**Pull request merged**
