### PR TITLE
Import and export raw audio data files (without ffmpeg)

### PR DESCRIPTION
**Pull request by miguelgrinberg**
This change adds support for reading and writing files with raw audio data in them, without the overhead of using conversions with ffmpeg.

Let me know what you think. Thanks!

### CODE REVIEW

**Comment by jiaaro** [comment]
Interesting - I don't know much about raw audio files, but I'm definitely _for_ supporting more formats without using ffmpeg.

I haven't had a chance to go over this thoroughly (been at a conf this weekend) but wanted to let you know I saw your PR. Might need to add more details to the docs since opening raw files doesn't (seem to) work the same way as other file types, but I'm planning to take a closer look at this soon.

At first glance it looks good!

(Also reminds me of the missed opportunity in not supporting AIFF natively. Nobody's asked for it, but… someday)

**Comment by miguelgrinberg** [comment]
Raw files are basically the data portion of the wav file, without any headers. You have to know what the sample size, # of channels, etc. are, so I have added those as extra arguments.

I'm working on a little application that will be recording audio segments with pyportaudio. These recordings come as raw data in byte arrays, so I want to wrap them as audio segments efficiently to then operate on them.

Thanks, and let me know if you need any changes made.

**Comment by jiaaro** [comment]
Made a few additions to the docs and issued a release to PyPI. Thanks!

**Comment by miguelgrinberg** [comment]
Awesome. Thank you!

**Pull request merged**
