### PR TITLE
Fix large file read

### PR DESCRIPTION
**Pull request by aj-cloete**
Fixed an issue where the `read()` command returned an error due to large file size.

### CODE REVIEW

**Comment by jiaaro** [comment]
I'm not familiar with this behavior of read? it acts differently with a very large read size than it does with non specified/

**Comment by aj-cloete** [comment]
I also found it rather strange.  Explicitly passing a large number into read removes the error.

**Comment by jiaaro** [comment]
Would it be better to do the read/write in chunks? maybe a megabyte at a time?

Also, is there a benefit to attempting the operation without the read size first?

**Comment by aj-cloete** [comment]
@jiaaro Chunking could also be a feasible solution.  I opted for the `try-except` block to keep implementation standard except when it fails.  
The files I am trying to load are `.mpg` format and about 4gb a piece.  I can open and play it using ffmpeg in bash but when I try to load it with `.from_file()` I get the OSError.  After addressing the OSError, it is returning a `cannot decode` error.  I will revert once I managed to get it working.

**Comment by jiaaro** [comment]
I just realized, `2**13` is only 8 kb of data - so if that solved the problem, either some data was missing, or the except block was only handling the last chunk of data

**Comment by drorpip** [comment]
Is there still a limitation with size file? I got exception on 4GB
File is above 300GB

**Pull request merged**
